<?php

/**
 * Implements hook_help().
 */
function portfolio_help($path, $arg)
{
    switch ($path){
        case 'admin/help#portfolio': {
            $ret_val = '<h3>' .t('About'). '</h3>';
            $ret_val.='<p>'. t('A content type to manage and make a quick template. Includes title, description, image and link to the project.').'</p>';
            return $ret_val;
            break;
        }
    }
}

/**
 * Implements hook_permission().
 */
function portfolio_permission()
{
    return array(
        'administer portfolio generator' =>  array(
            'title' => t('Administer Potfolio Generator'),
            'description' => t('Perform administration tasks for portfolio generator.'),
        ),
    );
}

/**
 * Implements hook_menu().
 */
function portfolio_menu()
{
    $items['portfolio'] = array(
    'title' => 'Portfolio',
    'page callback' => 'portfolio_node_view',
    'access callback' => TRUE,
    'menu_name' => 'main-menu',  // This is the changed line.
    'type' => MENU_NORMAL_ITEM,
    );
    return $items;
}



/**
 * Implements hook_node_view().
 */

function portfolio_node_view()
{
    drupal_add_css(drupal_get_path('module','portfolio').'/css/portfoliostyle.css');

    $nodes = node_load_multiple(array(), array('type' => 'portfolio'));
        if ($nodes != Null) {
            foreach ($nodes as $node) {
                $alias = url(drupal_get_path_alias('node/' . $node->nid), array('absolute' => TRUE));
                $img = theme('image', array('path' => $node->portfolio_content_image[LANGUAGE_NONE][0]['uri']));
                $text = text_summary($node->portfolio_content_fill[LANGUAGE_NONE][0]['value'], $format=NULL, $size = 250);
                $a[] = array(
                    '#prefix' => '<article class="row">',
                    '#suffix' => '</article>',
                    'title' => array(
                        '#prefix' => '<h2 class="title1">',
                        '#markup' => l($node->title,$alias),
                        '#suffix' => '</h2>'.'<br>',
                    ),
                );

                if($img!=NULL){
                    $a[] = array(
                        'pic' => array(
                            '#markup' => $img,
                        ),
                    );
                }
                $a[] = array(
                    'body' => array(
                        '#prefix' => '<p class="lead">',
                        '#markup' => '<br>'.$text.l(t(' more..'),$alias),
                        '#suffix' => '</p>',
                    ),
                );
                if($node->portfolio_content_link!=NULL){
                    $a[] = array(
                        'link' => array(
                            '#markup' => '<br>'.t('Link: ').l($node->portfolio_content_link[LANGUAGE_NONE][0]['title'],$node->portfolio_content_link[LANGUAGE_NONE][0]['url']).'<hr><br>',
                        ),
                    );
                } else{
                    $a[] = array(
                      '#markup' => '<hr><br>',
                    );
                }

            }
        } else {
            $a = t('There is no item in portfolio.');
        }
        return $a;
}


/**

function portfolio_view($node, $view_mode, $langcode = NULL)
{
    $node = 'portfolio';
    $view_mode = 'full';
    return $node;
}

/**function _portfolio_page_creator(){
    $sql_query  = 'SELECT * ';
    $sql_query .= 'FROM {node} ';
    $sql_query .= 'WHERE type = :type ';
    $result = db_query($sql_query, array(':type' => 'portfolio'));

    $fields = field_info_instances("node","portfolio");
    dpm($fields);
}
 * **/